function interfata(G,A,C,N,x,poz,post,T,meciuri)
im=strcat('echipa/',num2str(x),'.jpg');%salvarea caii de acces catre poza...
%jucatorului
figure('Name','Club Atlético de Madrid',...
 'Units','normalized',...
 'Position',[0.15 0.2 0.5 0.6],...
 'NumberTitle','off');
 %crearea unor axe care vor strapunge intreaga interfata grafica
ah1 = axes('unit', 'normalized', 'position', [0 0 1 1]); 
%importarea imaginii de background si afisarea ei pe axe
bg1= imread('wanda.jpg'); 
image(bg1);
% dezactivarea axelor
set(ah1,'handlevisibility','off','visible','off')
%o masura in plus pentru a fi siguri ca backgroundul este in spatele...
%tuturor obiectelor
uistack(ah1, 'bottom');
%inceput popupmenu
uicontrol('Style','PopupMenu',...
 'Units','normalized',...
 'Position',[0.14 0.85 0.12 0.07],...
 'String',N,...
 'value',poz,...
 'Callback','i=get(gco, ''string''),poz=get(gco, ''value''),[x]=extragere(i,poz),[G,A,meciuri,post]=citire(x),[C]=calculeaza(x,T,G,A,meciuri,post),close,interfata(G,A,C,N,x,poz,post,T,meciuri)');
%sfarsit popupmenu
%inceput poza jucator
ah1 = axes('unit', 'normalized', 'position', [0.1 0.5 0.2 0.3]); 
%importarea imaginii de background si afisarea ei pe axe
bg1= imread(im); 
image(bg1);
% dezactivarea axelor
set(ah1,'handlevisibility','off','visible','off')
%sfarsit poza jucator
%inceput nume jucator
uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.445 0.2 0.04],...
 'foregroundcolor','black',...
 'String',N(poz))
%sfarsit nume jucator
%inceput text group
uibuttongroup('Visible','on',...
 'BackgroundColor','r',...
'ForegroundColor','black',...
 'Title','Parametrii:',...
 'FontSize',10,...
'TitlePosition','centertop',...
 'Tag','textbutton',...
 'Position',[0.07 0.06 0.15 0.37]);
%sfarsit text group
%inceput tag-uri
switch post
    case 'Portar'
        uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.335 0.10 0.04],...
 'foregroundcolor','black',...
 'String','Meciuri fara gol');
uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.25 0.10 0.04],...
 'foregroundcolor','black',...
 'String','Goluri incasate')
    otherwise 
     uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.335 0.10 0.04],...
 'foregroundcolor','black',...
 'String','Goluri');  
uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.25 0.10 0.04],...
 'foregroundcolor','black',...
 'String','Pase de gol')
end
uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.15 0.10 0.04],...
 'foregroundcolor','black',...
 'String','Meciuri')
%sfarsit text
%inceput edit group
uibuttongroup('Visible','on',...
 'BackgroundColor','r',...
'ForegroundColor','black',...
 'Title','Calcule:',...
 'FontSize',10,...
'TitlePosition','centertop',...
 'Tag','textbutton',...
 'Position',[0.23 0.06 0.15 0.37]);
%sfarsit edit group
%inceput edit
edit_G=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.25 0.35 0.10 0.04],...
 'foregroundcolor','black',...
 'String',G,...
 'Callback',['G=','str2num(get(gco,''String''))']');
edit_A=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.25 0.25 0.10 0.04],...
 'foregroundcolor','black',...
 'String',A,...
 'Callback',['A=','str2num(get(gco,''String''))']');
if(G<0)
    set(edit_G,'backgroundcolor','y','String','Error');
end
if(A<0)
    set(edit_A,'backgroundcolor','y','String','Error');
    A='ERROR';
end
%sfarsit edit
%inceput meciuri
uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.25 0.15 0.10 0.04],...
 'foregroundcolor','black',...
 'String',meciuri);
%sfarsit meciuri
%inceput grafic
subplot(122);
t=2018:1:2018+T-1;
bar(t,exp(sqrt(C))*3);
grid on; %plasam caroiaj
title('Cota de piata a unui jucator raportata la perfomante');
%atribuim un titlu graficului
xlabel('Ani','FontSize',12,'FontWeight','bold'); 
%scriem text pe axa x
ylabel('Cota de piata(mil.€)','FontSize',12,'FontWeight','bold'); 
%scriem text pe axa y
%sfarsit grafic
%inceput documentatie
f=uimenu('Label','Documentatie');
uimenu(f,'Label','Prezentare','Callback','Prezentare');
uimenu(f,'Label','Teorie','Callback','Teorie');
uimenu(f,'Label','Bibliografie','Callback','Bibliografie');
 uimenu(f,'Label','Autor','Callback','Autor');
 uimenu(f,'Label','Inchide','Callback','close',...
 'Separator','on','Accelerator','C');
%sfarsit documentatie
%inceput buton calculeaza
uicontrol('Style','pushbutton',...
 'Units','normalized',...
 'Position',[0.87 0.02 0.10 0.04],...
 'String','Calculeaza',...
 'Callback','close,[C]=calculeaza(x,T,G,A,meciuri,post),interfata(G,A,C,N,x,poz,post,T,meciuri)');
%sfarsit buton calculeaza

